### ISSUE TITLE
Loading and processing a replay from memory

### ISSUE THREAD

**Issue by deissh** [circleguard/circlecore#158]
It would be helpful to add a way to load the replay directly from memory. For example, load a file from s3 and transfer it to circlecore without saving a temporary file.

**Comment by tybug** [comment]
there's a lot of different ways a replay could be represented in memory...what object specifically do you have that you would like to load a replay from?

**Comment by deissh** [comment]
any

io.StringIO, os.BytesIO

**Comment by tybug** [comment]
if you mean that you have a text stream that came from a 
```python
with open("replay.osr", "r"):
    stream = r.read()
```
or some similar operation, and would like to use `stream` to load a replay, I can add that. I do wonder why you don't have access to the file itself from s3 though (I've never used s3 so I don't know what the constraints are).
