### ISSUE TITLE
Usernames are "None" when doing user investigation

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circlecore#177]
![Circleguard_ah0Ijc6kEY](https://user-images.githubusercontent.com/28674643/145716431-b4433853-1675-44a4-b23e-1fd5cdd8392b.png)
Context: https://discord.com/channels/532476765860265984/532476765860265986/919571888206921739

**Comment by tybug** [comment]
was actually already fixed by ad5a0d54c9bf892109279d706219f8eca88aed84, just needed to do a version bump
