### ISSUE TITLE
matplotlib error with waiting for input

### ISSUE THREAD

**Issue by tybug** [circleguard/circlecore#43]
while waiting for y/n input this appears

```
invalid command name "4584907080_on_timer"
    while executing
"4584907080_on_timer"
    ("after" script)
```

never happens on first comparison, seems to be related to closing the graph and not letting it finish. Inconsistent, doesn't always happen second time etc.

**Comment by tybug** [comment]
Keeping this issue open for now due to the relative rarity of the bug.

**Comment by InvisibleSymbol** [comment]
It just happened to me again, so this isn't fixed

**Comment by tybug** [comment]
Much appreciated, looks like I don't understand how matplotlib errors work after all. Same output and everything?

**Comment by InvisibleSymbol** [comment]
Looks to be the same output, but to be safe I attached a screenshot
![](http://i.imgur.com/kjFoSXw.png)

**Comment by InvisibleSymbol** [comment]
Circlecore 2.0 is now a pip module, so this doesn't apply anymore.
