### ISSUE TITLE
Corrupted replay returned by api

### ISSUE THREAD

**Issue by tybug** [circleguard/circlecore#61]
Command to reproduce: `python circleguard.py -m 91 -n 100`

api url: `https://osu.ppy.sh/api/get_replay?k=KEY&m=0&b=91&u=965485`

trace: https://cdn.discordapp.com/attachments/539956865245904906/549032218484408330/Screenshot_1.png

Most likely an upstream issue for one reason or another, but we can certainly prevent it from being fatal on our end.

**Comment by InvisibleSymbol** [comment]
`python .\circleguard.py -m 91 -u 965485 -n 2` is a faster way to reproduce the error, if anyone needs it

**Comment by tybug** [comment]
this issue references a pre 1.0.0 version of circleguard, but the issue wasn't fixed until now. Fixed in e5cce13274843a08e14a776bc4c53568c829ade9
