### ISSUE TITLE
setup.py breaks if missing requirements (release branch)

### ISSUE THREAD

**Issue by InvisibleSymbol** [circleguard/circlecore#85]
![](https://i.imgur.com/feGeLgq.png)
`from circleguard.version import __version__`
This line causes `__init__.py` to load which attempts to import requirements not yet installed (they would be automatically installed later)

**Comment by tybug** [comment]
not even a `version.py` is safe...totally forgot importing it causes `__init__.py` to trigger. Now I understand why SO was saying to parse the file without importing it. Which is what we'll have to do to fix this. (`with open("./circleguard/version.py") as f`)

**Comment by tybug** [comment]
Should be fixed with c05bc1c4a86c8f0ea57dc426405e479f2654ccf5
