### ISSUE TITLE
[release] add possibility to set slider cache location

### ISSUE THREAD

**Issue by InvisibleSymbol** [circleguard/circlecore#97]
Slider implementation on circleguard will use a permanent location for storing the database. This could theoretically be shared with circlecore to lower strain on the api.

Note that it should be a path, not a file. Slider will dump the `*.osu` files in same dir as the `.slider.db`

**Comment by tybug** [comment]
Added by 0e5fabd7207bbf0cf1803c421cdc0bd147fd755e
